### ISSUE TITLE
ValueError: (InvalidArgument) The 2-th dimension of input tensor is expected to be equal with the 2-th dimension of output tensor 2 or 1, but received 0.   [Hint: Expected in_dim[in_idx] == out_dims[in_idx] || in_dim[in_idx] == 1 == true, but received in_dim[in_idx] == out_dims[in_idx] || in_dim[in_idx] == 1:0 != true:1.] (at ../paddle/p hi/kernels/funcs/dims_simplifier.h:144)

### ISSUE THREAD

**Issue by LRuiRui517** [yeyupiaoling/PP-YOLOE#16]
Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\train.py", line 43, in <module>
    trainer.train(num_epoch=args.num_epoch,
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\ppyoloe\trainer.py", line 300, in train
    self.__train_epoch(max_epoch=num_epoch, epoch_id=epoch_id, log_interval=log_interval, local_rank=local_rank, writer=writer)
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\ppyoloe\trainer.py", line 204, in __train_epoch
    output = self.model(data)
  File "C:\Users\DELL\.conda\envs\lrp\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\ppyoloe\model\meta_arch.py", line 53, in forward
    out = self.get_loss()
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\ppyoloe\model\yolo.py", line 46, in get_loss
    return self._forward()
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\ppyoloe\model\yolo.py", line 36, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "C:\Users\DELL\.conda\envs\lrp\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\ppyoloe\model\ppyoloe_head.py", line 202, in forward
    return self.forward_train(feats, targets)
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\ppyoloe\model\ppyoloe_head.py", line 142, in forward_train
    return self.get_loss([
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\ppyoloe\model\ppyoloe_head.py", line 308, in get_loss
    self.assigner(
  File "C:\Users\DELL\.conda\envs\lrp\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\DELL\.conda\envs\lrp\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\DELL\.conda\envs\lrp\lib\site-packages\paddle\fluid\dygraph\base.py", line 347, in _decorate_function
    return func(*args, **kwargs)
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\ppyoloe\model\task_aligned_assigner.py", line 93, in forward
    ious = iou_similarity(gt_bboxes, pred_bboxes)
  File "C:\Users\DELL\Desktop\PP-YOLOE-master\ppyoloe\model\bbox_utils.py", line 42, in iou_similarity
    x2y2 = paddle.minimum(px2y2, gx2y2)
  File "C:\Users\DELL\.conda\envs\lrp\lib\site-packages\paddle\tensor\math.py", line 1172, in minimum
    return _C_ops.minimum(x, y)
ValueError: (InvalidArgument) The 2-th dimension of input tensor is expected to be equal with the 2-th dimension of output tensor 2 or 1, but received 0.
  [Hint: Expected in_dim[in_idx] == out_dims[in_idx] || in_dim[in_idx] == 1 == true, but received in_dim[in_idx] == out_dims[in_idx] || in_dim[in_idx] == 1:0 != true:1.] (at ../paddle/p
hi/kernels/funcs/dims_simplifier.h:144)
I have this problem and I don't know how to solve it.

**Comment by yeyupiaoling** [comment]
我也没有看出什么问题
