### ISSUE TITLE
训练中断

### ISSUE THREAD

**Issue by Liang-Z8** [yeyupiaoling/PP-YOLOE#2]
您好，我在用voc格式的数据集训练中每迭代一千次左右（每次中断时间不同）就会报错：

> 2020-10-02 20:42:48,441-WARNING: fail to map op [Gt2YoloTarget_82e929] with error: index 18 is out of bounds for axis 2 with size 16 and stack:
Traceback (most recent call last):
  File "C:\Users\LHT\Anaconda3\envs\paddle\lib\site-packages\ppdet\data\reader.py", line 46, in __call__
    data = f(data, ctx)
  File "C:\Users\LHT\Anaconda3\envs\paddle\lib\site-packages\ppdet\data\transform\batch_operators.py", line 258, in __call__
    target[best_n, 0, gj, gi] = gx * grid_w - gi
IndexError: index 18 is out of bounds for axis 2 with size 16
每次会中断训练，重新开始训练会在不同的位置出现这个问题。

**Comment by yeyupiaoling** [comment]
@Liang-Z8 根据错误提示，这应该给是某一个标注数据出现了问题，最好写个程序，看看全部的标注文件格式是否符合voc格式

**Comment by yeyupiaoling** [comment]
没有问题我就关闭了
